Repository DevTrackClub/DevTrackWebsite, pull requests merged in 2022-10, with the labels that each got.

#11 Move JS code from index.html to index.js
  src/index.html
  src/index.js
Labels: hactoberfest-accepted

#22 Scroll top btn added
  index.html
  index.js
  styles.css
Labels: hactoberfest-accepted

#23 Auto generate Contributors section in README
  README.md
Labels: hacktoberfest-accepted

#25 Changed font and styling for mission and vision
  index.html
Labels: hacktoberfest-accepted

#31 Favicon added
  favicon.png
  index.html
Labels: hacktoberfest-accepted

#33 Added heart in footer
  index.html
  styles.css
Labels: hacktoberfest-accepted

#37 improved go to top button
  index.html
  styles.css
Labels: hacktoberfest-accepted

#32 Card flip animation for the tracks card
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#41 FIXED TRACK CARD ISSUE
  index.html
  styles.css
Labels: hacktoberfest-accepted, PR:Ready-to-Review

#52 Feature/responsivness
  .vscode/settings.json
  index.html
  styles.css
Labels: hacktoberfest-accepted

#62 text aligment fixed
  styles.css
Labels: hacktoberfest-accepted

#65 Fix: Inconsistency of bubble plus icon on mobile screen
  styles.css
Labels: hacktoberfest-accepted
